# fly.toml app configuration file generated for piccy-eater on 2024-01-20T13:17:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "piccy-eater"
primary_region = "lhr"

[build]
  dockerfile = "./Dockerfile.prod"
  ignorefile = "./.dockerignore"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  NODE_ENV = "production"
  PORT = "3000"