FROM node:19.0.0-alpine

RUN mkdir -p /usr/src/app

RUN chown -R node:node /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

USER node

CMD ["npm", "run", "start:dev:generate"]
