name: Health check

on:
  schedule:
    # '*' is a special character in YAML, hence the quotation marks
    - cron: '0 0 * * *'

jobs:
  health_check:
    name: 🩺 Check health of deployed app
    runs-on: ubuntu-latest
    steps:
      - name: Check deployed app responding at base URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://piccy-eater.fly.dev/
